// Public entry point for @hfkit/theme.
//
// `./generated/tokens.ts` is generated by `npm run generate` from
// tokens.json -- see that file's header, and README.md, before editing
// anything under src/generated/.

export type {
  ThemeName,
  StatusColorTokens,
  StatusRampTokens,
  SemanticTokens,
  ComponentTokens,
  DatavizTokens,
  ThemeTokens,
  PrimitiveTokens,
  SequentialRamp,
  CategoricalPalette,
} from "./generated/tokens.js";

export { themeNames, defaultTheme, primitives, themes, getTheme } from "./generated/tokens.js";

export { applyTheme, readStoredTheme } from "./theme-runtime.js";
